### ISSUE TITLE
Double event listener?

### ISSUE THREAD

**Issue by nstcactus** [statikbe/craft-sentry#1]
Just being  curious: why do you add 2 event listeners for the same event?

https://github.com/statikbe/craft-sentry/blob/20fc880f1fd6b40d35fbb7dc72442d9c023e9bf7/src/Sentry.php#L49
https://github.com/statikbe/craft-sentry/blob/20fc880f1fd6b40d35fbb7dc72442d9c023e9bf7/src/Sentry.php#L63

**Comment by janhenckens** [comment]
hey @nstCactus, no reason for that, just a boo boo. Thanks for catching that, fixed now!

**Comment by janhenckens** [comment]
Fixed in 1.0.1
